### ISSUE TITLE
articles with subarticles are not being handled correctly

### ISSUE THREAD

**Issue by domzae** [freichel/willitfit#96]
See [893.259.63](https://www.ikea.com/de/de/p/burhult-sibbhult-wandregal-weiss-weiss-s89325963/)
Expected result:
```
20,2,59,1.27,1,80400042,89325963,BURHULT
18,3,18,0.07,2,10417734,89325963,BURHULT
```
Plot should result in 3 packages.

Observed result:
```
20,2,59,1.27,1,80400042,89325963,BURHULT
20,2,59,1.27,1,10417734,89325963,BURHULT
```
![image](https://user-images.githubusercontent.com/40212333/121330221-1a249280-c916-11eb-9043-a3f874d22e62.png)

Also see [293.037.75](https://www.ikea.com/de/de/p/aepplaroe-3er-sitzelement-aussen-mit-hocker-braun-las-kuddarna-grau-s29303775/) for a more complex set of packages

**Comment by KasiaCieslik** [comment]
solved.
Output in database 
20,2,59,1.27,1,80400042,89325963,BURHULT
18,3,18,0.07,2,10417734,89325963,BURHULT
